################################# Default configuration ###################
defaultContentLanguage = "ja"

# provide your domain here
baseURL = "https://code-for-hamamatsu.github.io/vaccinecert-faq/"
# theme
theme = "dot-hugo"
# site title
title = "ワクチン接種証明書アプリFAQ"
# disable language
disableLanguages = ["en"]
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
title = "ワクチン接種証明書アプリFAQ"
description = "このサイトはデジタル庁が公開した新型コロナワクチン接種証明書アプリのオープンデータ接種証明書アプリFAQを利用したFAQサイトです。"
author = "Themefisher"
image = "images/icon.jpg" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#B10020"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Noto Sans JP" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "#"

HasCJKLanguage = true

[languages]
  ################################ Japanese Language ######################
  [Languages.ja]
  languageName = "日本語"
  languageCode = "ja-jp"
  weight = 1
  copyright = "Copyright &copy; 2021 Code For Hamamatsu"

  # banner
  [Languages.ja.params.banner]
  title = "ワクチン接種証明書アプリFAQ"
  subtitle = ""
  # bg_image = "images/banner.jpg"
  placeholder = "お知りになりたいことは何ですか？"

  # # call to action
  # [Languages.ja.params.cta]
  # enable = true
  # title = "Didn't find an answer to your question?"
  # content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
  # # call to action button
  # [Languages.ja.params.cta.button]
  # enable = true
  # label = "contact us"
  # link = "contact"


  ################## Japanese navigation #################
  [[Languages.ja.menu.main]]
  name = "About"
  url = "about"
  weight = 1

  # [[Languages.ja.menu.main]]
  # name = "Faq"
  # url = "faq"
  # weight = 2

  # [[Languages.ja.menu.main]]
  # name = "contact"
  # url = "contact"
  # weight = 3

  # # Dropdown menu
  # [[Languages.ja.menu.main]]
  # weight = 4
  # name = "docs"
  # hasChildren = true

  #   [[Languages.ja.menu.main]]
  #   parent = "docs"
  #   name = "Installation"
  #   url = "installation"
  #   weight = 1

  #   [[Languages.ja.menu.main]]
  #   parent = "docs"
  #   name = "Billing and Pricing"
  #   url = "billing-pricing"
  #   weight = 2

  #   [[Languages.ja.menu.main]]
  #   parent = "docs"
  #   name = "Features"
  #   url = "features"
  #   weight = 3

  ################################ English Language ######################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  weight = 2
  copyright = "Copyright &copy; 2021 a Hugo theme by [Gethugothemes](https://gethugothemes.com/)"

  # banner
  [Languages.en.params.banner]
  title = "Support Center & Knowledge base"
  subtitle = "Find advice and answers from our support team fast or get in touch"
  bg_image = "images/banner.jpg"
  placeholder = "Have a question? Just ask here or enter terms"

  # # call to action
  # [Languages.en.params.cta]
  # enable = true
  # title = "Didn't find an answer to your question?"
  # content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
  # # call to action button
  # [Languages.en.params.cta.button]
  # enable = true
  # label = "contact us"
  # link = "contact"


  ################## english navigation #################
  [[Languages.en.menu.main]]
  name = "Home"
  url = ""
  weight = 1

  [[Languages.en.menu.main]]
  name = "Faq"
  url = "faq"
  weight = 2

  # [[Languages.en.menu.main]]
  # name = "contact"
  # url = "contact"
  # weight = 3

  # # Dropdown menu
  # [[Languages.en.menu.main]]
  # weight = 4
  # name = "docs"
  # hasChildren = true

  #   [[Languages.en.menu.main]]
  #   parent = "docs"
  #   name = "Installation"
  #   url = "installation"
  #   weight = 1

  #   [[Languages.en.menu.main]]
  #   parent = "docs"
  #   name = "Billing and Pricing"
  #   url = "billing-pricing"
  #   weight = 2

  #   [[Languages.en.menu.main]]
  #   parent = "docs"
  #   name = "Features"
  #   url = "features"
  #   weight = 3


  ################################### Franch Language ######################
  # [Languages.fr]
  # languageName = "Fr"
  # languageCode = "fr-fr"
  # weight = 3
  # copyright = "Copyright &copy; 2021 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

  # # banner
  # [Languages.fr.params.banner]
  # title = "Comment pouvons nous aider?"
  # subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
  # bg_image = "images/banner.jpg"
  # placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

  # # call to action
  # [Languages.fr.params.cta]
  # enable = true
  # title = "Vous n'avez pas trouvé de réponse à votre question?"
  # content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
  # # call to action button
  # [Languages.fr.params.cta.button]
  # enable = true
  # label = "Contactez nous"
  # link = "contact"


  # ################## french navigation #################
  # [[Languages.fr.menu.main]]
  # name = "Accueil"
  # url = "/"
  # weight = 1

  # [[Languages.fr.menu.main]]
  # name = "Faq"
  # url = "faq"
  # weight = 2

  # [[Languages.fr.menu.main]]
  # name = "contact"
  # url = "contact"
  # weight = 3

  # # Dropdown menu
  # [[Languages.fr.menu.main]]
  # weight = 4
  # name = "docs"
  # hasChildren = true

  #   [[Languages.fr.menu.main]]
  #   parent = "docs"
  #   name = "Installation"
  #   url = "installation"
  #   weight = 1

  #   [[Languages.fr.menu.main]]
  #   parent = "docs"
  #   name = "Billing and Pricing"
  #   url = "billing-pricing"
  #   weight = 2

  #   [[Languages.fr.menu.main]]
  #   parent = "docs"
  #   name = "Features"
  #   url = "features"
  #   weight = 3

